[tool.poetry]
name = "sgfcup"
version = "0.1.0"
description = ""
authors = ["russelg <isaac.drew@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.5"
jinja2 = "^2.11.2"
cymysql = "^0.9.14"
bottle = {git = "https://github.com/bottlepy/bottle.git"}
python-magic = "^0.4.18"
pillow = "^7.1.2"
pygments = "^2.6.1"
jsonmerge = "^1.7.0"
tornado = "^6.0.4"
bottle-beaker = "^0.1.3"
beaker = "^1.11.0"
ghdiff = "^0.4"
future = "^0.18.2"
pycrypto = "^2.6.1"

[tool.poetry.dev-dependencies]
raven = "^6.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
